# Generated by Django 4.2.7 on 2023-11-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_used_count',
            field=models.IntegerField(default=0),
        ),
    ]
