# Generated by Django 4.2.7 on 2023-11-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0002_ticket_total_used_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodcontainer',
            name='intro',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='today_limit',
            field=models.IntegerField(default='5'),
        ),
    ]
