# Generated by Django 4.2.7 on 2023-11-24 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0003_foodcontainer_intro_alter_ticket_today_limit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foodcontainer',
            options={'ordering': ['-created_at']},
        ),
    ]
