# Generated by Django 4.2.7 on 2023-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatting', '0005_foodcontainer_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foodcontainer',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to='chatting/thumbnail/'),
        ),
    ]
